name: Build and Push Docker Images

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up versioning
        id: vars
        run: |
            echo "VERSION=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Build and push gremilins/nextcloudffmpeg image
        run: |
          docker build -t gremilins/nextcloudffmpeg:${{ env.VERSION }} .
          docker push gremilins/nextcloudffmpeg:${{ env.VERSION }}
          docker tag gremilins/nextcloudffmpeg:${{ env.VERSION }} gremilins/nextcloudffmpeg:latest
          docker push gremilins/nextcloudffmpeg:latest
