name: Build and Push Docker Images

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:    
      - name: Checkout code
        uses: actions/checkout@main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up versioning
        id: vars
        run: echo "VERSION=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Build and push gremilins/nextcloudffmpeg image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            gremilins/nextcloudffmpeg:${{ env.VERSION }}
            gremilins/nextcloudffmpeg:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=gremilins/nextcloudffmpeg:buildcache
          cache-to: type=inline
